### ISSUE TITLE
Add to rating stars with github stars & used by

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/novapackages#10]
From @lorenzosapora (tightenco/novapackages-issues#67):

Much like #6, the rating system is underused, and prone to initial gaming. I make a package, I 5 star it (or my puppet account does), and I have instant credibility.

If the cards included at least one of the metrics (used by, watch, star, fork), and possibly all of that information once on the package page itself, the ratings could be more authentic, at a glance.

**Comment by mattstauffer** [comment]
(Be sure to check the original thread for some back-and-forth)

**Comment by andrewmile** [comment]
We are now displaying the following banner at the top of any packages that appear to be abandoned, abandoned being defined as either of the following:
- The package is marked as abandoned on Packagist
- The package is older than 15 days and has no releases (this accounts for new packages)

**code change:**
https://github.com/tightenco/novapackages/blob/73413450be4e4685aa8ca4c7a43a9c6b15ae8462/app/Http/Resources/PackageDetailResource.php#L91-L98

![image](https://user-images.githubusercontent.com/1121383/73221699-21833b80-4127-11ea-8903-99dce9709c68.png)

**Comment by andrewmile** [comment]
PR #14 was added to prevent users from rating packages they either authored or contributed to.  

In addition, the package details page now displays the number of Github stars and Packagist downloads.
