### ISSUE TITLE
When not logged in, I get an empty state

### ISSUE THREAD

**Issue by devingray** [tightenco/novapackages#25]
Nova Packages, when not logged in shows an empty state on package detail

![Screenshot 2020-02-04 at 11 15 32](https://user-images.githubusercontent.com/11573528/73713398-2b97d200-4705-11ea-9a4c-908f9a9d0bf3.png)

After logging in, everything works fine

**Comment by mattstauffer** [comment]
Thanks! Fixed already.

**Comment by devingray** [comment]
Awesome
