### ISSUE TITLE
The author id field is required

### ISSUE THREAD

**Issue by NormanHuth** [tightenco/novapackages#50]
I can't submit a nova package. I get the message: 

> The author id field is required

But I have filled in all mandatory fields.

![novapackages](https://user-images.githubusercontent.com/26193232/77010933-12707b00-696b-11ea-9cf1-479a6f13a7ba.jpg)

**Comment by mattstauffer** [comment]
Whoops! This is a Vue problem in the midst of us converting the site to Livewire. We'll get on it!

**Comment by mattstauffer** [comment]
@NormanHuth Fixed. Thanks!!
