### ISSUE TITLE
Search not working DOM wire:id error

### ISSUE THREAD

**Issue by tanthammar** [tightenco/novapackages#52]
The search does not work all the time. This happens since you swapped to livewire.

Reproduce:
Go to the frontpage.
Click on "resource tools"
Enter something in the search input.
Check the console.

error:
````
Livewire Error:

Cannot find parent element in DOM tree containing attribute: [wire:id].

Usually this is caused by Livewire's DOM-differ not being able to properly track changes.

Reference the following guide for common causes: https://laravel-livewire.com/docs/troubleshooting 

Referenced element:

<g id="Page-1" stroke="none" stroke-width="1" fill-rule="evenodd">
                        <g id="icon-shape">
                            <polygon id="Combined-Shape" points="9.29289322 12.9497475 10 13.6568542 15.6568542 8 14.2426407 6.58578644 10 10.8284271 5.75735931 6.58578644 4.34314575 8"></polygon>
                        </g>
                    </g>
```

**Comment by mattstauffer** [comment]
Huh, I haven't run into that yet, but thanks for sharing!

I tried to reproduce but can't:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/151829/77942867-49f3f700-728a-11ea-9714-ff261b503a7f.png">

Can you tell me a little more about your browser or what you typed? I'm confident this is a real problem, I just need to figure out how to reproduce it.

Thanks!

**Comment by mattstauffer** [comment]
Ahh, when I un-searched then re-searched multiple times, I was able to trigger it! Let me add some debug info and see if I can fix it!

**Comment by mattstauffer** [comment]
Fixed. Thanks!
