### ISSUE TITLE
Report package

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/novapackages#9]
From @timcv (tightenco/novapackages-issues#63):

Hi, a button to report packages that is no longer maintaind or not working would be great so they could be removed.

This packages is removed, but still listed on novapackages.com.

https://novapackages.com/packages/jobcerto/nova-grid

**Comment by andrewmile** [comment]
We are now displaying the following banner at the top of any packages that appear to be abandoned, abandoned being defined as either of the following:
- The package is marked as abandoned on Packagist
- The package is older than 15 days and has no releases (this accounts for new packages)

**code change:**
https://github.com/tightenco/novapackages/blob/73413450be4e4685aa8ca4c7a43a9c6b15ae8462/app/Http/Resources/PackageDetailResource.php#L91-L98

![image](https://user-images.githubusercontent.com/1121383/73221699-21833b80-4127-11ea-8903-99dce9709c68.png)
